import express from "express";
import vendorRoutes from "./routes/vendor.routes.js";
import makeRoutes from "./routes/make.routes.js";
import accountRouter from "./routes/bankAccount.route.js";
import modelRouter from "./routes/models.route.js";
import moduleRouter from "./routes/module.routes.js";
import roleRouter from "./routes/roles.routes.js";
import workFlowRouter from "./routes/workFlow.route.js";
import cors from 'cors';
const app = express();
app.use(express.urlencoded({ extended: true }));
app.use(cors());
app.use(express.json());
app.use(express.json({ limit: "50mb" }));
app.use(express.urlencoded({ limit: "50mb", extended: true }));
app.use("/vendors", vendorRoutes);
app.use("/make",makeRoutes);
app.use("/account",accountRouter);
app.use("/models",modelRouter);
app.use("/modules",moduleRouter);
app.use("/roles",roleRouter);
app.use("/workFlow",workFlowRouter);
export default app;
